---
title: "MB5370 Presentation Waln"
author: "Ryan Waln"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

## Introduction

This file plots the AIMs data for the class presentation into the desired figures

```{r, message=FALSE, warning=FALSE, include=FALSE}
# R Setup & housekeeping
knitr::opts_chunk$set(
	echo = TRUE,
	include = TRUE,
	message = FALSE,
	warning = FALSE)

rm(list=ls())
objects()
```

```{r}
# Packages
library(tidyverse)
```


```{r}
library(sf)
library(tmap)
library(ozmaps)
library(dplyr)

# Get Queensland outline
qld <- ozmap_states |> filter(NAME == "Queensland")

tm_shape(qld) +
  tm_borders(col = "black", lwd = 0.8) +
  tm_fill(col = "lightgoldenrodyellow") +
  tm_layout(title = "Queensland Coast", frame = FALSE)
```
```{r}

```

